# PLEASE CHANGE FOR YOUR OWN ENVIRONMENT
NET_SSID = '<<YOUR_WIFI_SSID>>'
NET_PASS = '<<YOUR_WIFI_PASSWORD>>'

SB_API_TOKEN = '<<YOUR_SWITCHBOT_API_TOKEN>>'

NTP_HOST = 'pool.ntp.org'
UTC_OFFSET = 9*3600

# PLEASE CHANGE TO YOUR LANGUAGE
DESC_TEXT_SCHEDULESETTING = '実行する時刻とシーンを設定してください'
DESC_TEXT_REGISTSCENES    = '登録するシーンを選択してください'
DESC_TEXT_NOSCHEDULE      = '--- スケジュールが設定されていません ---'

DESC_TEXT_EVERYDAY = '毎　日'
DESC_TEXT_MONDAY   = '月曜日'
DESC_TEXT_TUESDAY  = '火曜日'
DESC_TEXT_WEDNESDAY= '水曜日'
DESC_TEXT_THURSDAY = '木曜日'
DESC_TEXT_FRIDAY   = '金曜日'
DESC_TEXT_SATURDAY = '土曜日'
DESC_TEXT_SUNDAY   = '日曜日'
DESC_TEXT_MON2THU  = '月～木'
DESC_TEXT_WEEKDAYS = '月～金'
DESC_TEXT_FRI2SUN  = '金土日'
DESC_TEXT_WEEKEND  = '土・日'

DESC_BUTTON_REGIST = '登録'
DESC_BUTTON_APPEND = '追加'
DESC_BUTTON_CHANGE = '変更'
DESC_BUTTON_DELETE = '削除'

DESC_BUTTON_REGISTCANCEL = '登録せず戻る'
DESC_BUTTON_APPENDCANCEL = '追加せず戻る'
DESC_BUTTON_CHANGECANCEL = '変更せず戻る'

DESC_BUTTON_ADDSCHEDULE = 'スケジュール追加'
DESC_BUTTON_EXECTEST    = 'テスト'
DESC_BUTTON_TIMEADJUST  = '時刻校正'
DESC_BUTTON_SCENEREGIST = '使用シーン登録'

